'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Badge} from '@/components/ui/badge';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
type Any=any;
const fmt=(v:Any)=>v===null||v===undefined?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:3});
function References({ids,workspace}:{ids:string[],workspace:Any}){
 return <p className="muted small">{ids.map((id,i)=>{const s=workspace.citations.find((s:Any)=>s.id===id)??workspace.sources.find((s:Any)=>s.id===id);return s?<span key={id}>{i>0?' · ':''}<a className="underline" href={s.url} target="_blank" rel="noreferrer">{s.title??s.name}</a></span>:null;})}</p>;
}
export function FacilityHypotheses({workspace,facilityId}:{workspace:Any,facilityId:string}){
 const rows=workspace.facilityHypotheses.filter((h:Any)=>h.facilityId===facilityId);
 return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">OSINT + STANDARD PROCESS EXPECTATIONS</p><h2>Working facility model</h2></div><Badge variant="outline">{rows.length} hypotheses</Badge></div><p className="callout">Best guesses make the operating model useful. All items below are INFERRED; confidence is qualitative. They do not establish actual purchases, installed equipment or capacity.</p><div className="archetype-grid">{rows.map((h:Any)=><article className="claim" key={h.id}><div className="flex gap-2 flex-wrap"><Badge variant="outline" className="tag blue">INFERRED</Badge><Badge variant="outline">{h.confidence} confidence</Badge></div><h3 className="mt-3">{h.area}</h3><ul className="plain-list">{h.items.map((item:string)=><li key={item}>{item}</li>)}</ul><p>{h.basis}</p><details><summary className="cursor-pointer link-label">Evidence, alternatives and verification</summary><p><strong>Alternative:</strong> {h.alternative}</p><p><strong>Verify or disprove:</strong> {h.verify}</p><References ids={h.sourceIds} workspace={workspace}/><p className="muted small">{h.id} · reviewed {h.reviewedAt} · review due {h.reviewDue}</p></details></article>)}</div></section>;
}
export default function CoverageView({workspace:w}:{workspace:Any}){
 const [query,setQuery]=useState('');
 const rows=w.benchmarks.filter((b:Any)=>`${b.label} ${b.geography} ${b.referencePeriod}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="section-intro"><p>Use public measurements and explicit assumptions to close gaps without inventing company data.</p><span>{w.benchmarks.length} reviewed measurements</span></div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">REFERENCE PERIOD ≠ RETRIEVAL DATE</p><h2>Public benchmark ledger</h2></div></div><p className="callout">Government measurements are confirmed within their published scope. Watershed impact remains inferred. These series do not backfill executive history, and a manually verified observation can coexist with a blocked automated endpoint.</p><Input aria-label="Filter public benchmarks" placeholder="Filter ingredient, packaging, energy or metro" value={query} onChange={e=>setQuery(e.target.value)} className="my-4"/><Table><TableHeader><TableRow><TableHead>Benchmark / geography</TableHead><TableHead>Latest value</TableHead><TableHead>Comparison</TableHead><TableHead>Period / release</TableHead><TableHead>Evidence</TableHead></TableRow></TableHeader><TableBody>{rows.map((b:Any)=><TableRow key={b.id}><TableCell><strong>{b.label}</strong><small>{b.geography} · {b.seriesCode??b.sourceId}</small></TableCell><TableCell>{fmt(b.value)} {b.unit}<small>{b.seasonalAdjustment}{b.preliminary?' · preliminary':''}</small></TableCell><TableCell>{b.comparison}{b.previousValue!==undefined&&<small>Prior: {fmt(b.previousValue)} ({b.previousPeriod})</small>}{b.yearOverYear!==null&&b.yearOverYear!==undefined&&<small>Year over year: {fmt(b.yearOverYear)}% ({b.yearOverYearSeasonalAdjustment??'NSA'})</small>}</TableCell><TableCell>{b.referencePeriod}<small>Released: {b.releaseDate??'exact day unverified'}</small></TableCell><TableCell><a className="underline" href={b.url} target="_blank" rel="noreferrer">Primary source</a><small>Retrieved {b.retrievedAt}</small></TableCell></TableRow>)}</TableBody></Table><p className="muted small">SA = seasonally adjusted; NSA = not seasonally adjusted. Do not compare differently adjusted changes as if they were a single weighted basket.</p></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">WHAT WE CAN INFER · WHAT WE CAN VERIFY</p><h2>Coverage and resolution ledger</h2></div></div><div className="archetype-grid">{w.coverageGaps.map((g:Any)=><article className="claim" key={g.id}><Badge variant="outline">{g.status}</Badge><h3 className="mt-3">{g.topic}</h3><p>{g.currentBasis}</p><dl className="decisions"><dt>Next public evidence</dt><dd>{g.publicNextStep}</dd><dt>Company verification</dt><dd>{g.internalVerification}</dd><dt>Interpretation limit</dt><dd>{g.boundary}</dd></dl><References ids={g.sourceIds} workspace={w}/><p className="muted small">{g.id} · reviewed {g.reviewedAt}</p></article>)}</div></section></>;
}
