"""Rebuild the public-source baseline. No private procurement or customer data."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data'
DATA.mkdir(exist_ok=True)
ASOF = '2026-09-17'
def save(name, value):
    (DATA / f'{name}.json').write_text(json.dumps(value, indent=2) + '\n')

refs = [
 ('ws-about','Watershed: About','https://watershedfoods.com/about','Company','Current company statement; not a registry of beneficial ownership.'),
 ('ws-capabilities','Watershed: Capabilities','https://watershedfoods.com/capabilities','Company','Advertised capability does not establish installed capacity or current production of every example.'),
 ('ws-markets','Watershed: Verticals','https://watershedfoods.com/verticals','Company','Market positioning, not customer contracts or category growth measurement.'),
 ('ws-careers','Watershed: Careers','https://watershedfoods.com/careers','Company','Public roles and regional facility descriptions; postings do not establish staffing levels.'),
 ('ws-home','Watershed: Food-safety statement','https://watershedfoods.com/','Company','SQF and safety-history claims are self-reported; certificate scope and expiry not inspected.'),
 ('edge-2024','Illinois DCEO: 2024 EDGE agreement','https://dceo.illinois.gov/content/dam/soi/en/web/dceo/expandrelocate/incentives/edge_agreements/2024-watershed-foods-llc-and-the-manna-group-llc-edge-agreement-redacted.pdf','Government','Dated agreement; planned investments and employment commitments are not proof of completion.'),
 ('topfox','Top Fox: About','https://topfoxsnacks.com/pages/about','Company','Brand ownership statement and contact location; no exhaustive supplier list.'),
 ('heartland-2026','Food Business News: Heartland transition','https://www.foodbusinessnews.net/articles/29579-watershed-foods-to-enter-popcorn-market-via-new-business-unit','Industry reporting','6 January 2026 interview; acquisition and expansion described as plans.'),
 ('deer-directory','Village of Deer Creek: Businesses','https://www.deercreekillinois.org/businesses.html','Government','Lists Aunt Em’s / Heartland at one address; does not prove transaction closing or throughput.'),
 ('wcbu-heartland','WCBU: Deer Creek grant','https://www.wcbu.org/local-news/2025-12-30/company-gets-1m-grant-to-expand-into-the-popcorn-business-in-deer-creek','Public media','30 December 2025; distinguish jobs created or retained from wholly new employment.'),
 ('ws-linkedin','Watershed public company profile','https://www.linkedin.com/company/watershed-foods','Company profile','Self-reported office location and founding year. Social profile is a discovery lead requiring verification.'),
 ('pantagraph-2009','Pantagraph: Watershed history','https://pantagraph.com/news/watershed-foods-success-driven-by-need-to-help-others/article_7a0f23b0-6f49-11de-8ec6-001cc4c03286.html','Historical reporting','Indexed excerpt retrieved; full article inaccessible. Historical customer only.'),
 ('tracegains','TraceGains: Watershed listing','https://gather.tracegains.com/market/supplier/587d731a-9c1a-42ef-bf2b-2d0d288df80a','Supplier directory','Document titles are not document contents, certificate validation, or evidence of a customer relationship.'),
 ('eia-diesel','EIA: Gasoline and Diesel Fuel Update','https://www.eia.gov/petroleum/gasdiesel/','Government','Regional retail on-highway diesel benchmark, not Watershed’s contracted fuel or freight rate.'),
 ('wasde-sep','USDA: September 2026 WASDE tables','https://www.usda.gov/oce/commodity/wasde/wasde0926.txt','Government','Forecast revisions; total grain figures are not popcorn- or food-grade ingredient quotations.'),
 ('fda-trace','FDA: Food Traceability Rule','https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-requirements-additional-traceability-records-certain-foods','Government','FDA describes a proposed date extension and a congressional non-enforcement direction; determine food/form/exemption applicability.'),
 ('fda-lead','FDA: Lead guidance, final PDF','https://www.fda.gov/media/164684/download','Government','January 2025 nonbinding guidance; footnote 2 excludes grain-based and freeze-dried snack foods.'),
 ('appa','APPA: Industry Trends and Stats','https://americanpetproducts.org/industry-trends-and-stats','Trade association','2026 figures are projections. Page has inconsistent prior-year headings; do not compute year-on-year growth from them.'),
 ('thrive','Thrive Freeze Dry','https://www.thrivefreezedry.com/','Company','Competitor capability statement; no market-share estimate.'),
 ('thrive-oak','Thrive: Oak Creek announcement','https://www.thrivefreezedry.com/thrive-foods-sets-up-one-of-the-largest-freeze-drying-facilities-in-north-america-to-further-enhance-capabilities/','Company','4 January 2023 announcement; commissioning and current utilization require re-verification.'),
 ('thrive-mercer','Thrive: Mercer combination','https://www.thrivefreezedry.com/entrepreneurial-equity-partners-and-mubadala-capital-private-equity-invest-in-mercer-foods-and-thrive-foods/','Company','Historical combination announcement; do not count Mercer as an independent alternative.'),
 ('vdf','Van Drunen Farms','https://www.vandrunenfarms.com/','Company','Advertised ingredient processing and blending capabilities.'),
 ('efd','European Freeze Dry','https://europeanfreezedry.com/','Company','Advertised food ingredients, contract drying and pet offerings.'),
 ('barrett','Barrett Petfood','https://barrettpetfood.com/','Company','Advertised petfood, freeze-dried and kibble capabilities.'),
 ('weaver','Weaver Popcorn Manufacturing','https://www.weaverpopcorn.com/','Company','Public popcorn co-manufacturing and private-label capabilities.'),
 ('flagstone','Flagstone Foods','https://flagstonefoods.com/','Company','Indexed company description supports private-label snacks; full-page fetch timed out.'),
]
citations = [dict(id=i,title=t,url=u,kind=k,retrievedAt=ASOF,limitation=l) for i,t,u,k,l in refs]
save('citations',citations)

facts=[]
def fact(i,topic,statement,cls,refs,note='',asof=ASOF):
    facts.append(dict(id=i,topic=topic,statement=statement,evidenceClass=cls,sourceIds=refs,asOf=asof,retrievedAt=ASOF,note=note,reviewDue='2026-12-17' if cls=='CONFIRMED' else None))
fact('F01','Ownership & leadership','Watershed describes itself as family-owned and names Jeremy Zobrist as CEO.','CONFIRMED',['ws-about'],'The statement does not identify equity percentages or all owners.')
fact('F02','Entity relationship','Watershed Foods LLC and The Manna Group LLC jointly signed an Illinois EDGE agreement.','HISTORICAL',['edge-2024'],'Co-participation establishes a relationship, not a parent/subsidiary direction.','2024-04-18')
fact('F03','Gridley','The state agreement identifies the project at 202 North Ford Street, Gridley. Current company recruiting describes Gridley freeze-drying.','CONFIRMED',['edge-2024','ws-careers'])
fact('F04','Expansion','The 2024 project proposed depositing, freezing, traying, freeze-drying and packaging additions, with a 31 December 2026 benchmark.','HISTORICAL',['edge-2024'],'Completion and installed line status remain unverified.','2024-04-18')
fact('F05','History','Watershed says its origins were supplying ingredients to large cereal producers.','HISTORICAL',['ws-about'])
fact('F06','History','The public company profile gives 2004 as the founding year.','HISTORICAL',['ws-linkedin'],'Self-reported profile; formation record not retrieved.')
fact('F07','Bloomington-Normal','A public company profile lists 2221 W College Avenue and Bloomington-Normal headquarters.','INFERRED',['ws-linkedin'],'Office/presence lead. Current headquarters designation and function need primary corroboration; do not replace Gridley manufacturing.')
fact('F08','Wisconsin','Watershed’s careers page describes baking and popping in greater Milwaukee.','CONFIRMED',['ws-careers'],'Street address, legal operator and line allocation are not established. Do not confuse Thrive’s Oak Creek plant with Watershed.')
fact('F09','Top Fox','Top Fox identifies Jeremy Zobrist as founder/owner and lists a Congerville contact address.','CONFIRMED',['topfox'],'1781 US Highway 150 is a public business contact location; exact operational footprint not established.')
fact('F10','Related businesses','CFO Derek Karr described Top Fox and Aunt Em’s as Watershed sister companies.','HISTORICAL',['heartland-2026'],'Relationship described in a January interview; legal holding structure not established.','2026-01-06')
fact('F11','Heartland / Aunt Em’s','Watershed planned to purchase Aunt Em’s equipment and transition operations to Heartland Food Solutions during 2026.','HISTORICAL',['heartland-2026'],'No verified closing date or completed expansion.','2026-01-06')
fact('F12','Deer Creek','The village directory lists Aunt Em’s / Heartland at 404 E. First Avenue.','CONFIRMED',['deer-directory'])
fact('F13','Leadership','Derek Karr was identified as CFO of Watershed and Heartland.','HISTORICAL',['heartland-2026'],'Dated role attribution, not an evergreen executive roster.','2026-01-06')
fact('F14','Processing','Watershed advertises freeze-dried, baked, roasted and popped platforms.','CONFIRMED',['ws-capabilities'])
fact('F15','Products','Public offerings span yogurt melts, fruit/vegetables, supplement blends, pet toppers, baked kibble/treats, nuts/seeds, legumes and popcorn.','CONFIRMED',['ws-capabilities'],'Capability examples do not establish current sales volume or a specific bill of materials.')
fact('F16','Markets','Watershed markets to toddler nutrition, human snacks and pet nutrition.','CONFIRMED',['ws-markets'])
fact('F17','Commercial model','The company describes international customers, private label, R&D and commercialization support.','CONFIRMED',['ws-about'],'No current customer names or revenue mix verified.')
fact('F18','Supporting processes','Gridley recruiting describes blending, packaging, cold forming, maintenance and shipment coordination.','CONFIRMED',['ws-careers'])
fact('F19','Storage','A dated state staffing schedule includes warehousing. Dedicated cold/frozen storage capacity is not established.','HISTORICAL',['edge-2024'],'Process freezing does not prove a separately operated cold-storage facility.','2024-04-18')
fact('F20','Powders / dairy','Watershed’s public directory lists freeze-dried powders, dietary supplements and animal-nutrition offerings.','CONFIRMED',['tracegains'],'Directory is corroboration for advertised capabilities only. In-house yogurt culturing or dairy processing steps remain unverified.')
fact('F21','Food safety','Watershed’s website claims SQF Level 3 certification and zero safety incidents.','CONFIRMED',['ws-home'],'Confirmed as a company claim only. Valid certificate, scope, expiry and exhaustive regulatory history not verified.')
fact('F22','Historical customers','A July 2009 newspaper excerpt named Kellogg’s as a freeze-dried fruit customer.','HISTORICAL',['pantagraph-2009'],'Full article not retrieved. Do not transfer this relationship to current Kellogg successor entities.','2009-07-13')
fact('F23','Current customers','No named current customer was verified to the required standard in this baseline.','INFERRED',[],'Use archetypes. Directory document labels, retailer listings and conference attendance do not prove direct supply contracts.')
fact('F24','Unresolved entities','TraceGains contains a powder-facility entry and Bauderer Packaging / Addison document labels.','INFERRED',['tracegains'],'Discovery leads only. No extra Watershed-owned facility, supplier or customer node is confirmed from these labels.')
fact('F25','Affiliations','Watershed publicly states support for Lifesong for Orphans.','CONFIRMED',['ws-about'],'Charitable support does not establish ownership by Lifesong or a Manna foundation.')
fact('F26','Top Fox inputs','Top Fox describes a pumpkin-farming origin and markets pumpkin and sunflower seed snacks.','CONFIRMED',['topfox'],'No claim that every seed is grown on one farm or in one country.')
save('ground-truth',facts)

facilities = [
 dict(id='gridley',name='Gridley',entity='Watershed Foods',location='Gridley, Illinois · McLean County',address='202 North Ford Street',precision='Public facility address',evidenceClass='CONFIRMED',sourceIds=['edge-2024','ws-careers'],platforms=['Freeze-dried'],context='Core manufacturing; public expansion benchmark is 31 December 2026.',unknowns=['Expansion commissioning','Utility contracts and backup capacity','Inbound crop origins','Cold-storage capacity','Rail use and carrier allocation']),
 dict(id='congerville',name='Congerville / Top Fox',entity='Top Fox Snacks',location='Congerville, Illinois · Woodford County',address='1781 US Highway 150',precision='Public business contact address',evidenceClass='CONFIRMED',sourceIds=['topfox','heartland-2026'],platforms=['Roasted'],context='Seed-snack brand and public Congerville presence; production footprint requires confirmation.',unknowns=['Exact production allocation','Seed origins and contracts','Roasting utilization','Utility provider']),
 dict(id='deer-creek',name='Deer Creek / Heartland',entity='Heartland Food Solutions / Aunt Em’s',location='Deer Creek, Illinois · Tazewell County',address='404 E. First Avenue',precision='Village business directory',evidenceClass='CONFIRMED',sourceIds=['deer-directory','heartland-2026'],platforms=['Popped'],context='Popcorn business; 2026 equipment transition and expansion announced.',unknowns=['Transaction close','Added shifts and lines commissioned','Expansion completion','Shipping contracts']),
 dict(id='wisconsin',name='Greater Milwaukee',entity='Watershed Wisconsin operation',location='Greater Milwaukee, Wisconsin',address=None,precision='Region only',evidenceClass='CONFIRMED',sourceIds=['ws-careers'],platforms=['Baked','Popped'],context='Company-described operation; regional weather and labor watch only.',unknowns=['Facility identity and municipality','Exact processes and line allocation','Legal operating entity','Utility and transport exposure']),
 dict(id='bloomington',name='Bloomington-Normal',entity='Watershed public-profile presence',location='Bloomington-Normal, Illinois',address=None,precision='Uncorroborated office lead',evidenceClass='INFERRED',sourceIds=['ws-linkedin'],platforms=[],context='Do not model as additional manufacturing capacity.',unknowns=['Current headquarters designation','Office or operating function','Facility status']),
]
save('facilities',facilities)

categories=['Ingredient availability','Ingredient cost','Customer demand','Transportation / logistics','Energy / utilities','Packaging','Labor','Food safety / regulatory','Cyber / OT','Facility / weather','Geopolitical / trade','Growth opportunity']
save('categories',categories)

exposure_rows=[
 ('Dairy / yogurt',['Freeze-dried'],['Toddler nutrition','Ingredients'],'Advertised yogurt products',['ws-capabilities'],'Upper Midwest and other milk basins','Milk solids, cultures, refrigeration, allergens','Dairy quotes → solids cost → margin; verify pass-through and actual yogurt sourcing.'),
 ('Fruit',['Freeze-dried'],['Toddler nutrition','Ingredients','Human snacks'],'Advertised fruit products',['ws-capabilities'],'California / Pacific Northwest / import origins are hypotheses','Irrigation, harvest, freezing, reefer freight','Crop stress → grade/yield → qualified fruit availability; crop geography must be verified.'),
 ('Vegetables',['Freeze-dried'],['Ingredients','Toddler nutrition'],'Advertised vegetables',['ws-capabilities'],'U.S. and international growing regions unverified','Water, crop disease, residue and contaminant controls','Crop variability → specifications/rejections → ingredient availability.'),
 ('Pumpkin / sunflower seeds',['Roasted'],['Human snacks','Private label'],'Top Fox products documented',['topfox'],'Central Illinois farming origin; other sourcing unknown','Crop region, drying, food-grade seed quality','Seed harvest/quality → roasting yield and cost; no field-corn price proxy for pepitas.'),
 ('Nuts',['Roasted'],['Human snacks'],'Capability advertised',['ws-capabilities'],'California and other origins are hypotheses','Water, allergen segregation, harvest labor','Drought/quality → graded-nut cost and availability.'),
 ('Soy / edamame',['Roasted','Baked'],['Human snacks','Pet nutrition'],'Hypothesis',[],'U.S. Midwest / imported specialty soy hypotheses','Identity preservation, allergen controls, processing','Food-grade and non-GMO premiums may decouple from soybean futures.'),
 ('Grains / popcorn',['Popped','Baked'],['Human snacks','Pet nutrition','Private label'],'Popcorn and grain capabilities advertised',['ws-capabilities'],'Midwest food-grade growing regions; actual sources unknown','Variety, moisture, oils, packaging film','Grain crop signals are contextual; popping-grade contracts require separate evidence.'),
 ('Chickpeas / legumes',['Roasted'],['Human snacks'],'Capability advertised',['ws-capabilities'],'Northern Plains / Canada / other origins hypotheses','Harvest moisture, protein quality, freight','Legume availability → roasting program capacity and alternative-protein launches.'),
 ('Proteins',['Freeze-dried','Baked'],['Pet nutrition','Dietary supplements'],'Product domain documented; individual inputs unknown',['ws-capabilities'],'Animal and plant protein origins unverified','Validated pathogen controls, segregation, cold chain','Protein disruptions → approved formulation options; no unvalidated substitution.'),
 ('Oils',['Roasted','Popped','Baked'],['Human snacks','Pet nutrition'],'Hypothesis',[],'Soy/canola/sunflower regions hypotheses','Oilseed crush, refining, shipping, identity','Oil benchmarks → recipe-dependent input costs; actual oil types unverified.'),
 ('Flavors / seasonings',['Roasted','Popped','Baked'],['Human snacks','Pet nutrition'],'Hypothesis',[],'Domestic blenders and import origins unverified','Spices, dairy powders, allergens, import controls','Spice/cheese powder disruptions → reformulation qualification lead time.'),
 ('Sweeteners',['Freeze-dried','Popped','Baked'],['Toddler nutrition','Human snacks'],'Hypothesis',[],'Sugar/corn supply regions hypotheses','Sugar policy, specialty sweeteners, formulation','Price or labeling changes → cost and claims review.'),
 ('Cultures / probiotics',['Freeze-dried'],['Toddler nutrition','Dietary supplements','Pet nutrition'],'Probiotic capability advertised',['ws-capabilities'],'Strain/IP owner and production country unknown','Viability, specialist fermentation, cold chain','Supplier/strain dependency → product viability and qualification risk.'),
 ('Functional ingredients',['Freeze-dried','Baked'],['Dietary supplements','Pet nutrition'],'Supplement capability advertised',['ws-capabilities'],'Unverified origins','Premix, testing, claims substantiation','New claims or contaminant rules → testing and formulation work.'),
 ('Film / cartons / labels / pallets',['Freeze-dried','Baked','Roasted','Popped'],['Private label','Contract manufacturing'],'Packaging confirmed; materials inferred',['ws-careers'],'Converter/resin/mill geography unverified','PE/PP/resin, paperboard, printing, freight','Shared converter/resin dependencies → effective redundancy; validate food-contact and barrier specs.'),
 ('Sanitation / processing inputs',['Freeze-dried','Baked','Roasted','Popped'],['Contract manufacturing'],'Necessary process hypotheses',[],'Chemical and consumable origins unknown','Approved chemicals, water, filters, spare parts','Approved-input disruption → sanitation schedule and release risk.'),
]
exposures=[dict(id='X%02d'%(i+1),ingredient=a,platforms=b,markets=c,basis=d,sourceIds=e,geography=f,dependencies=g,pathway=h,evidenceClass='INFERRED',spendShare=None,volume=None,substitutability='Uncalibrated; QA/customer approval required') for i,(a,b,c,d,e,f,g,h) in enumerate(exposure_rows)]
save('exposures',exposures)

archetypes=[
 ('Global CPG / Fortune 500','All four','Earnings volumes, inventory, procurement and reformulation','Outsourced innovation or portfolio simplification','Insourcing, SKU rationalization and destocking'),
 ('Cereal manufacturers','Freeze-dried','Cereal volumes, fruit inclusions, plant moves','Premium inclusions and shelf-life solutions','Cereal weakness or recipe simplification'),
 ('Toddler / baby nutrition brands','Freeze-dried; Baked','Launches, recalls, cohort demand, contaminant controls','Qualified melts and convenient formats','Lower birth cohorts, recalls, tighter formulation needs'),
 ('Healthy-snack companies','Roasted; Popped; Baked; Freeze-dried','Units vs price/mix, distribution wins, protein launches','Seeds, legumes and differentiated textures','Promotion pressure and consumer trade-down'),
 ('Pet-food brands','Freeze-dried; Baked','Kibble-plus launches, earnings volume, channel inventories','Toppers, inclusions and mixed textures','Premium trade-down or owned capacity expansion'),
 ('Pet-treat brands','Freeze-dried; Baked','Treat frequency, functional claims, retailer assortment','Functional treats with validated process controls','Claims restrictions and lower discretionary spending'),
 ('Supplements / functional nutrition','Freeze-dried; Baked','Novel formats, ingredient regulation, claims evidence','Stable portioned formats and custom blends','Claims enforcement, ingredient shortages'),
 ('Retail / private label','All four','Private-label units, retailer margin, shelf resets','Value-tier innovation and category expansion','Tender concentration and price compression'),
 ('Emerging CPG','All four','Funding, launch velocity, distribution, cash constraints','Pilot-to-scale process and packaging support','Funding failure, small order economics'),
 ('International food manufacturers','Freeze-dried; All four','Trade policy, FX, import rules and market launches','Shelf-stable exportable ingredients and formats','Tariffs, registration delays, logistics disruption'),
]
save('demand',[dict(id=f'D{i+1:02}',name=a,platforms=b,monitor=c,upside=d,downside=e,customerStatus='Archetype; no named current account asserted',watershedMix=None) for i,(a,b,c,d,e) in enumerate(archetypes)])

source_rows=[
 ('nws-il','NWS Illinois alerts','https://www.weather.gov/documentation/services-web-api','https://api.weather.gov/alerts/active?area=IL','nws',1,3,'Facility / weather','Gridley, Congerville, Deer Creek; filter county geocodes before facility attribution'),
 ('nws-wi','NWS Wisconsin alerts','https://www.weather.gov/documentation/services-web-api','https://api.weather.gov/alerts/active?area=WI','nws',1,3,'Facility / weather','Wisconsin regional lead only until facility municipality is verified'),
 ('drought','U.S. Drought Monitor','https://droughtmonitor.unl.edu/','https://droughtmonitor.unl.edu/','page',168,240,'Ingredient availability','Weekly; supplier-crop origin mapping required'),
 ('noaa-cpc','NOAA climate outlooks','https://www.cpc.ncep.noaa.gov/','https://www.cpc.ncep.noaa.gov/','page',24,48,'Facility / weather','Excessive heat, freeze, seasonal planting/harvest conditions'),
 ('river','NOAA National Water Prediction Service','https://water.noaa.gov/','https://water.noaa.gov/','page',6,12,'Transportation / logistics','Mississippi/Illinois river; no assumed company barge use'),
 ('usgs','USGS water services','https://waterservices.usgs.gov/','https://waterservices.usgs.gov/','page',6,12,'Transportation / logistics','Select relevant gauges only after route exposure is validated'),
 ('ams-dairy','USDA AMS Dairy Market News','https://www.ams.usda.gov/market-news/dairy','https://www.ams.usda.gov/market-news/dairy','page',24,72,'Ingredient cost','Milk, yogurt solids, butter, cheese and dry dairy products; weekly reports'),
 ('ams-specialty','USDA AMS specialty crops','https://www.ams.usda.gov/market-news/fruits-vegetables','https://www.ams.usda.gov/market-news/fruits-vegetables','page',24,72,'Ingredient cost','Fruit, vegetables, nuts and seeds; report-specific grade and region'),
 ('nass','USDA NASS publications','https://www.nass.usda.gov/Publications/','https://www.nass.usda.gov/Publications/','page',24,72,'Ingredient availability','Crop progress weekly in season; acreage/yield/milk/cold storage on release calendar'),
 ('nass-quickstats','USDA NASS Quick Stats API','https://quickstats.nass.usda.gov/api','https://quickstats.nass.usda.gov/api/api_GET/','key',24,72,'Ingredient availability','NASS_API_KEY and explicit commodity/geography queries required; include pumpkins where measured'),
 ('wasde','USDA WASDE','https://www.usda.gov/oce/commodity/wasde','https://www.usda.gov/oce/commodity/wasde','page',24,960,'Ingredient availability','Monthly projections: corn, soybeans, wheat, oils and international crop conditions'),
 ('fas','USDA FAS world production','https://fas.usda.gov/data','https://fas.usda.gov/data','page',24,72,'Ingredient availability','International crop and trade reports; match species and supplier geography'),
 ('cme','CME agricultural markets','https://www.cmegroup.com/markets/agriculture.html',None,'manual',24,48,'Ingredient cost','Futures licensing and basis matter; no implied executable quotes or hedging instruction'),
 ('eia-diesel','EIA diesel','https://www.eia.gov/petroleum/gasdiesel/','https://www.eia.gov/petroleum/gasdiesel/','diesel',24,216,'Transportation / logistics','Weekly Midwest benchmark; fuel surcharge clauses are unknown'),
 ('eia-energy','EIA electricity, gas, petroleum','https://www.eia.gov/opendata/','https://www.eia.gov/opendata/','page',24,72,'Energy / utilities','Daily/weekly gas and petroleum; monthly industrial electricity prices'),
 ('eia-api','EIA structured API','https://www.eia.gov/opendata/documentation.php','https://api.eia.gov/v2/','key',24,72,'Energy / utilities','EIA_API_KEY and selected regional industrial series required'),
 ('miso','MISO grid conditions','https://www.misoenergy.org/','https://www.misoenergy.org/','page',6,12,'Energy / utilities','Regional grid conditions; site balancing area and utility unverified'),
 ('ameren','Ameren Illinois outages','https://www.ameren.com/illinois/outage-center',None,'manual',1,3,'Energy / utilities','Public map requires interactive review; no confirmed Watershed utility relationship'),
 ('we-energies','Wisconsin utility outage watch','https://www.we-energies.com/outages/',None,'manual',1,3,'Energy / utilities','Regional source; do not assign provider until exact Wisconsin facility is known'),
 ('usda-transport','USDA grain transportation report','https://www.ams.usda.gov/services/transportation-analysis/gtr','https://www.ams.usda.gov/services/transportation-analysis/gtr','page',24,216,'Transportation / logistics','Weekly truck, rail, barge and ocean context, not Watershed lane pricing'),
 ('bts','Bureau of Transportation Statistics','https://www.bts.gov/','https://www.bts.gov/','page',168,336,'Transportation / logistics','Freight and intermodal indicators with publication lag'),
 ('stb','Surface Transportation Board service data','https://www.stb.gov/reports-data/rail-service-data/','https://www.stb.gov/reports-data/rail-service-data/','page',24,216,'Transportation / logistics','Rail service conditions; facility use remains hypothesis'),
 ('illinois-roads','Getting Around Illinois','https://www.gettingaroundillinois.com/',None,'manual',6,12,'Facility / weather','Road closures/construction; publicly visible regional travel only'),
 ('wisconsin-roads','511 Wisconsin','https://511wi.gov/',None,'manual',6,12,'Facility / weather','Weather and road conditions; no inferred last-mile exposure'),
 ('usace','USACE navigation notices','https://ndc.ops.usace.army.mil/','https://ndc.ops.usace.army.mil/','page',24,48,'Transportation / logistics','Locks, river navigation and closures; validate lane dependency'),
 ('marad','MARAD maritime advisories','https://www.maritime.dot.gov/msci','https://www.maritime.dot.gov/msci','page',6,24,'Geopolitical / trade','Suez, Hormuz, Bab-el-Mandeb; elevate only through a sourced causal path'),
 ('panama','Panama Canal advisories','https://pancanal.com/en/maritime-services/','https://pancanal.com/en/maritime-services/','page',24,48,'Transportation / logistics','Transit capacity and restrictions; no assumed route'),
 ('port-la','Port of Los Angeles statistics','https://www.portoflosangeles.org/business/statistics','https://www.portoflosangeles.org/business/statistics','page',168,840,'Transportation / logistics','Port/container activity; use actual import port when known'),
 ('fda-recalls','FDA food enforcement API','https://open.fda.gov/apis/food/enforcement/','https://api.fda.gov/food/enforcement.json?sort=report_date:desc&limit=100','fda',6,24,'Food safety / regulatory','Reporting lag and 100-record window; product/firm/lot matching required; not a complete recall clearance'),
 ('fda-alerts','FDA safety alerts','https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts','https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts','page',6,24,'Food safety / regulatory','Human and animal products; public notices complement enforcement data'),
 ('fda-warning','FDA warning letters','https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/compliance-actions-and-activities/warning-letters','https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/compliance-actions-and-activities/warning-letters','page',24,72,'Food safety / regulatory','Firm identity and observation dates; a warning letter is not a recall'),
 ('fda-import','FDA import alerts','https://www.accessdata.fda.gov/cms_ia/ialist.html','https://www.accessdata.fda.gov/cms_ia/ialist.html','page',24,48,'Geopolitical / trade','Commodity/country/facility match and effective dates required'),
 ('fda-fsma','FDA FSMA updates','https://www.fda.gov/food/food-safety-modernization-act-fsma','https://www.fda.gov/food/food-safety-modernization-act-fsma','page',24,72,'Food safety / regulatory','Human food, animal food, sanitation, FSVP and traceability applicability'),
 ('fda-trace','FDA traceability implementation','https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-requirements-additional-traceability-records-certain-foods','https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-requirements-additional-traceability-records-certain-foods','page',24,72,'Food safety / regulatory','Separate proposed rules, enacted enforcement limits and final obligations'),
 ('fda-cvm','FDA animal food','https://www.fda.gov/animal-veterinary/animal-food-feeds','https://www.fda.gov/animal-veterinary/animal-food-feeds','page',24,72,'Food safety / regulatory','Pet labeling, claims, pathogens and animal-food preventive controls'),
 ('fda-toddler','FDA Closer to Zero','https://www.fda.gov/food/environmental-contaminants-food/closer-zero-reducing-childhood-exposure-contaminants-foods','https://www.fda.gov/food/environmental-contaminants-food/closer-zero-reducing-childhood-exposure-contaminants-foods','page',24,72,'Food safety / regulatory','Product forms, age groups, state rules and guidance scope must be checked'),
 ('cdc','CDC foodborne outbreaks','https://www.cdc.gov/food-safety/outbreaks/','https://www.cdc.gov/food-safety/outbreaks/','page',6,24,'Food safety / regulatory','Category signals only until company/lot exposure is verified'),
 ('fsis','USDA FSIS recalls','https://www.fsis.usda.gov/recalls','https://www.fsis.usda.gov/recalls','page',6,24,'Food safety / regulatory','Where ingredient/product jurisdiction applies; no blanket USDA plant status'),
 ('idph','Illinois food safety','https://dph.illinois.gov/topics-services/food-safety.html','https://dph.illinois.gov/topics-services/food-safety.html','page',24,72,'Food safety / regulatory','State food protection and notices'),
 ('widatcp','Wisconsin DATCP','https://datcp.wi.gov/Pages/Programs_Services/FoodSafety.aspx','https://datcp.wi.gov/Pages/Programs_Services/FoodSafety.aspx','page',24,72,'Food safety / regulatory','Wisconsin licensing and food safety; actual operator must be resolved'),
 ('sqfi','SQFI developments','https://www.sqfi.com/','https://www.sqfi.com/','page',168,336,'Food safety / regulatory','SQF/GFSI scheme developments; verify certificate scope separately'),
 ('federal-register','Federal Register food/trade rules','https://www.federalregister.gov/','https://www.federalregister.gov/api/v1/documents.json?conditions[term]=food&order=newest&per_page=50','federal',24,48,'Food safety / regulatory','Public rule discovery; distinguish proposed/final/effective and agency jurisdiction'),
 ('cbp','CBP trade announcements','https://www.cbp.gov/trade','https://www.cbp.gov/trade','page',24,48,'Geopolitical / trade','Tariffs, enforcement and customs systems; HTS plus country plus entry date'),
 ('usitc','USITC Harmonized Tariff Schedule','https://hts.usitc.gov/','https://hts.usitc.gov/','page',24,48,'Geopolitical / trade','Do not assign a tariff from an ingredient name alone'),
 ('ustr','USTR trade actions','https://ustr.gov/','https://ustr.gov/','page',24,48,'Geopolitical / trade','Retaliation, import/export policy and official implementation details'),
 ('ofac','Treasury OFAC updates','https://ofac.treasury.gov/recent-actions','https://ofac.treasury.gov/recent-actions','page',24,48,'Geopolitical / trade','Country/entity screening; no unsupported counterparty relationship'),
 ('bls-ppi','BLS producer prices','https://www.bls.gov/ppi/','https://www.bls.gov/ppi/','page',24,960,'Packaging','Monthly resin, PE/PP, paperboard, corrugated, aluminum and labels proxies; not quotes'),
 ('afpa','AF&PA packaging statistics','https://www.afandpa.org/statistics-resources','https://www.afandpa.org/statistics-resources','page',168,960,'Packaging','Paper/paperboard demand; some reports require license'),
 ('bls-labor','BLS Midwest labor','https://www.bls.gov/regions/midwest/','https://www.bls.gov/regions/midwest/','page',24,840,'Labor','Illinois/Wisconsin unemployment, manufacturing employment, wages; metro aggregation'),
 ('ides','Illinois labor market information','https://ides.illinois.gov/resources/labor-market-information.html','https://ides.illinois.gov/resources/labor-market-information.html','page',24,840,'Labor','Central Illinois employment, local wages and WARN notices'),
 ('widwd','Wisconsin labor data','https://dwd.wisconsin.gov/wisconomy/','https://dwd.wisconsin.gov/wisconomy/','page',24,840,'Labor','Greater Milwaukee employment/wages until municipality is verified'),
 ('dol','Department of Labor policy','https://www.dol.gov/newsroom/releases','https://www.dol.gov/newsroom/releases','page',24,72,'Labor','Workforce policy changes; do not infer workforce immigration status'),
 ('sec','SEC EDGAR public filings','https://www.sec.gov/edgar/search/','https://www.sec.gov/edgar/search/','page',24,72,'Customer demand','Archetype watchlist: filings/earnings; SEC fair-access identity required for bulk data'),
 ('appa','APPA pet demand','https://americanpetproducts.org/industry-trends-and-stats','https://americanpetproducts.org/industry-trends-and-stats','page',168,960,'Customer demand','Annual estimates/projected value; not premium segment units'),
 ('plma','PLMA private-label category signals','https://plma.com/','https://plma.com/','page',168,336,'Customer demand','Private label, retailer commentary; some data licensed'),
 ('ws-careers','Watershed company changes','https://watershedfoods.com/careers','https://watershedfoods.com/careers','page',168,336,'Labor','Role/capability changes; vacancies alone do not establish shortage'),
 ('ws-about','Watershed company ground truth','https://watershedfoods.com/about','https://watershedfoods.com/about','page',168,336,'Growth opportunity','Leadership, scope and market changes; revalidate ownership claims quarterly'),
 ('topfox','Top Fox product watch','https://topfoxsnacks.com/','https://topfoxsnacks.com/','page',168,336,'Customer demand','Seeds, flavors and retail expansion; listings do not establish direct customer contracts'),
 ('deer-creek','Deer Creek public notices','https://www.deercreekillinois.org/','https://www.deercreekillinois.org/','page',24,72,'Facility / weather','Emergency conditions, utilities and public construction notices'),
 ('gridley-local','Gridley public notices','https://villageofgridley.org/','https://villageofgridley.org/','page',24,72,'Facility / weather','Local weather/emergency and public utility notices'),
 ('thrive','Thrive / Mercer capacity','https://www.thrivefreezedry.com/news/','https://www.thrivefreezedry.com/news/','page',168,336,'Growth opportunity','Group aliases de-duplicated; announcement is not commissioning'),
 ('vdf','Van Drunen capability watch','https://www.vandrunenfarms.com/','https://www.vandrunenfarms.com/','page',168,336,'Growth opportunity','Freeze-dried ingredients and powders'),
 ('efd','European Freeze Dry capacity','https://europeanfreezedry.com/','https://europeanfreezedry.com/','page',168,336,'Growth opportunity','International contract freeze-drying and pet products'),
 ('barrett','Barrett Petfood capacity','https://barrettpetfood.com/','https://barrettpetfood.com/','page',168,336,'Growth opportunity','Pet manufacturing and freeze-dried inclusions'),
 ('weaver','Weaver Popcorn capacity','https://www.weaverpopcorn.com/','https://www.weaverpopcorn.com/','page',168,336,'Growth opportunity','Private-label, microwave and ready-to-eat popcorn'),
 ('flagstone','Flagstone snack capacity','https://flagstonefoods.com/','https://flagstonefoods.com/','page',168,336,'Growth opportunity','Nuts, trail mix, plant consolidation; reverify each announcement'),
 ('pmmi','PMMI packaging automation','https://www.pmmi.org/','https://www.pmmi.org/','page',168,336,'Growth opportunity','Robotics, machine vision, equipment and workforce developments'),
 ('gea','GEA processing technology','https://www.gea.com/en/','https://www.gea.com/en/','page',168,336,'Growth opportunity','Freeze-drying and food processing; no Watershed vendor attribution'),
 ('rockwell','Rockwell product advisories','https://www.rockwellautomation.com/en-us/trust-center/security-advisories.html','https://www.rockwellautomation.com/en-us/trust-center/security-advisories.html','page',24,72,'Cyber / OT','PLC/HMI advisory discovery only; installed vendor/version unverified'),
 ('cisa-kev','CISA exploited vulnerabilities','https://www.cisa.gov/known-exploited-vulnerabilities-catalog','https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json','kev',6,24,'Cyber / OT','Cross-reference authorized software inventory; catalog presence does not prove exposure'),
 ('cisa-ics','CISA ICS advisories','https://www.cisa.gov/news-events/ics-advisories','https://www.cisa.gov/news-events/ics-advisories','page',6,24,'Cyber / OT','ICS/OT, PLC, HMI, SCADA and vendor compromise; no scanning of facilities'),
 ('cisa-ransom','CISA StopRansomware','https://www.cisa.gov/stopransomware','https://www.cisa.gov/stopransomware','page',24,48,'Cyber / OT','Food-sector, ERP/cloud/identity and supply-chain incidents with explicit pathways'),
]
verified={'nws-il','nws-wi','ams-dairy','wasde','eia-diesel','fda-recalls','fda-trace','bls-labor','appa','ws-careers','ws-about','topfox','deer-creek','gridley-local','thrive','vdf','efd','barrett','weaver'}
sources=[dict(id=i,name=n,url=u,endpoint=e,adapter=a,cadenceHours=c,staleHours=s,category=g,scope=l,priority=1 if i in ['nws-il','nws-wi','eia-diesel','fda-recalls','cisa-kev','fda-trace'] else 2,validation='Reference reviewed' if i in verified else 'Endpoint validation pending',retrievedAt=ASOF if i in verified else None,access='Key required' if a=='key' else 'Manual / licensed' if a=='manual' else 'Public',mode='Structured' if a in ['nws','kev','fda','federal','diesel'] else 'Page change / analyst review' if a=='page' else 'Configuration required') for i,n,u,e,a,c,s,g,l in source_rows]
save('sources',sources)

signals=[]
def sig(i,title,summary,cat,direction,conf,refs,fac,expo,factors,why,verify,action,trigger,roles,event,expiry,impact='Near',group=None):
    signals.append(dict(id=i,title=title,summary=summary,category=cat,direction=direction,confidence=conf,evidenceClass='INFERRED',sourceIds=refs,facilityIds=fac,exposureIds=expo,factors=dict(zip(['exposure','severity','confidence','persistence','velocity','dependency','substitutability'],factors)),factorRationale=why,causalPath=why,verify=verify,action=action,trigger=trigger,roles=roles,observedAt=event,retrievedAt=ASOF,reviewedAt=ASOF,expiresAt=expiry,timeToImpact=impact,impactDomains=[cat],status='reviewed',group=group or i,revision=1))
sig('S01','Midwest diesel rises 5.1% in a week','EIA’s 14 September Midwest diesel benchmark is $6.250/gal, up $0.304 from $5.946. Watershed’s actual surcharge exposure is unknown.','Transportation / logistics','Threat','Medium',['eia-diesel'],['gridley','congerville','deer-creek','wisconsin'],[],[75,70,70,70,80,80,35],'Retail diesel ↑ → carrier fuel surcharges → delivered costs. Exposure 75 assumes truck reliance; severity 70 reflects a 5.1% weekly move. Confidence 70, persistence 70, velocity 80, dependency 80 and substitutability 35 are provisional analyst judgments.','Freight contracts, surcharge lag, outbound miles and customer pass-through.','Ask logistics and finance to quantify surcharge sensitivity for the next shipping cycle.','Another >5% weekly rise or contracted transport costs >5% above plan.',['CFO','Supply Chain','COO','Customer Experience'],'2026-09-15','2026-09-24','Near','fuel-cost')
sig('S02','Grain outlook tightens; specialty basis still unknown','September WASDE projects U.S. total-grain ending stocks of 62.92 Mt versus 65.03 Mt in August. That is a broad context signal, not a popcorn forecast.','Ingredient availability','Mixed','Low',['wasde-sep'],['deer-creek','gridley','wisconsin'],['X07'],[45,55,45,80,45,55,60],'Broad grain balance → potential feed/grain pricing → formula costs. All seven factors are uncalibrated proxies (45/55/45/80/45/55/60); popping-grade corn and food-grade contracts can diverge materially.','Actual grains, specification basis, origin, contracts and inventory cover.','Track supplier quotations before changing coverage or formulations.','Two relevant supplier quotes worsen >10%, or verified cover falls below the approved operating threshold.',['Supply Chain','CFO'],'2026-09-11','2026-10-12','Tactical','grain-balance')
sig('S03','Traceability planning requires a product-form decision','FDA describes a proposed extension and a congressional direction not to enforce the rule before 20 July 2028. Applicability still depends on covered food and form.','Food safety / regulatory','Mixed','Medium',['fda-trace'],['gridley','congerville','deer-creek','wisconsin'],[],[55,65,65,90,25,70,60],'Covered receiving/transformation → KDE/CTE obligations → systems and partner coordination. Scope is not established for Watershed; factors 55/65/65/90/25/70/60 reflect planning exposure rather than a violation.','Food Traceability List applicability at each process stage; exemptions; customer contractual dates.','Quality and IT should map covered inputs and data exchanges, retaining product-specific legal review.','Final regulatory change, customer deadline, or a confirmed gap in an applicable traceability process.',['Quality / Food Safety','IT / Security','COO'],'2026-06-15','2026-10-17','Strategic','traceability')
sig('S04','Pet formats offer a qualified commercial opening','APPA projects $69.7bn of pet-food and treat sales for 2026. This does not establish unit growth or freeze-dried segment growth.','Growth opportunity','Opportunity','Low',['appa','ws-capabilities'],['gridley','wisconsin'],['X09','X13'],[70,60,45,85,45,65,65],'Pet-category spending → candidate launch budgets → topper/inclusion projects suited to advertised capabilities. Factors 70/60/45/85/45/65/65 reflect an unvalidated sales hypothesis, not Watershed revenue.','Premium segment units, brand launch plans, current capacity and qualified process fit.','Build a small list of qualified topper/inclusion prospects and test demand before reserving capacity.','Documented customer briefs and trial conversion, with confirmed available capacity and validated safety controls.',['Sales / Business Development','R&D / Innovation','CEO'],'2026-09-17','2026-12-17','Strategic','pet-demand')
sig('S05','Popcorn expansion is an opportunity to verify','Deer Creek’s public directory now lists Aunt Em’s / Heartland together. The reported equipment transition remains unverified as completed.','Growth opportunity','Opportunity','Medium',['deer-directory','heartland-2026'],['deer-creek'],['X07','X10','X11','X15'],[70,65,60,85,40,75,60],'Announced process additions → possible new formats → private-label prospects. Factors 70/65/60/85/40/75/60 assume qualification work; no incremental capacity is counted as operational.','Equipment ownership, commissioning, production qualification and available slots.','Confirm the production milestone before offering new formats or delivery commitments.','Verified commissioned capacity plus a qualified customer opportunity.',['COO','Sales / Business Development','Engineering','CEO'],'2026-01-06','2026-10-17','Tactical','popcorn-expansion')
sig('S06','Baby-food lead guidance has a material scope exclusion','The FDA final guidance excludes grain-based and freeze-dried snacks. It must not be applied automatically to every toddler product.','Food safety / regulatory','Mixed','High',['fda-lead'],['gridley'],['X01','X02','X03'],[70,70,85,90,20,75,50],'SKU classification → applicable contaminant requirements/customer specifications → testing and release criteria. Low velocity 20 reflects an existing rule, not new contamination. Other factors are analytical prioritization.','Each SKU’s form, age positioning, state rules and customer specifications.','Keep contaminant controls; have Quality document the correct guidance scope by SKU.','Changed FDA/state requirements or an actual out-of-spec result; then use the approved food-safety response process.',['Quality / Food Safety','R&D / Innovation'],'2025-01-06','2026-12-17','Tactical','toddler-scope')
save('signals',signals)

hyp=[
 ('H1','Higher dairy prices threaten yogurt-melt margins.',['F15','S01'],'Advertised yogurt products create a plausible solids-cost channel.','Pass-through, contracted inputs and actual category contribution are unknown.',45,'Milk/solids quotes; product contribution; pass-through lag','No material margin change across two sustained >10% input-price moves.'),
 ('H2','Premium pet spending increases demand for freeze-dried toppers.',['F15','S04'],'Advertised toppers align with a substantial pet category.','Dollar spend can reflect inflation; premium units and Watershed order mix are unknown.',45,'Segment units; launches; briefs; conversion to orders','Three periods of segment growth with no comparable qualified lead/order response.'),
 ('H3','Drought in a key fruit origin affects Watershed within 60 days.',['F15'],'Fruit processing establishes a possible channel.','No key source region or inventory cover is verified.',25,'Verified origin; drought; crop yield; contracted cover','Verified sourcing lies elsewhere or contracted supply/cover prevents a measurable 60-day effect.'),
 ('H4','Popcorn expansion adds corn, oils, cheese-powder, film and promotion exposures.',['F11','S05'],'Announced popcorn transition and process growth.','Commissioning, actual formulas and customer terms remain unknown.',60,'Operating milestone; formulas; packaging specifications; retail promotion orders','No production transition or relevant ingredients/formats in the confirmed portfolio.'),
 ('H5','Top Fox creates differentiated seed and roasting exposure.',['F09','F26'],'Seed products and the brand’s farming origin are public.','Origins, owned vs bought inputs and manufacturing allocation are unknown.',65,'Food-grade seed harvest; origin concentration; roasting yield','Verified production and input model has no incremental seed/roasting exposure.'),
 ('H6','Automation lowers labor exposure but raises OT and specialized-maintenance dependency.',['F18'],'Maintenance and engineering are public capabilities.','Automation intensity and measured labor productivity are unknown.',40,'Labor hours/unit; maintenance delays; software inventory; vendor dependency','Automation adds no measurable labor saving or dependency after controlled comparison.'),
]
save('hypotheses',[dict(id=i,title=t,evidenceFor=f,evidenceAgainst=a,sourceIds=ss,confidence=c,indicators=ind,falsification=fa,outcome='OPEN',failCount=0,revision=1,updatedAt=ASOF) for i,t,ss,f,a,c,ind,fa in hyp])
forecasts=[
 dict(id='P01',question='Will Midwest on-highway diesel exceed $6.250/gal for the week of 12 October 2026?',probability=.55,horizon='2026-10-12',resolutionDue='2026-10-16',confidence='Low',outcome=None,sourceIds=['eia-diesel'],indicators=['S01'],resolutionRule='Use the first EIA release reporting the week of 2026-10-12; strict greater-than $6.250. Missing/delayed release stays unresolved.',rationale='Recent benchmark momentum; no fitted forecasting model. Baseline judgment, not a commodity trade recommendation.',createdAt=ASOF),
 dict(id='P02',question='Will October WASDE project U.S. total-grain ending stocks below 65.03 Mt for 2026/27?',probability=.60,horizon='2026-10-09',resolutionDue='2026-10-16',confidence='Low',outcome=None,sourceIds=['wasde-sep'],indicators=['S02'],resolutionRule='Compare the October 2026 WASDE 2026/27 U.S. total-grain ending-stocks forecast in million metric tons with 65.03. Do not substitute corn-only data.',rationale='September forecast is below August, but the next revision is uncertain.',createdAt=ASOF),
 dict(id='P03',question='Will a primary public source confirm the Deer Creek equipment transition is operational by 31 March 2027?',probability=.55,horizon='2027-03-31',resolutionDue='2027-04-07',confidence='Low',outcome=None,sourceIds=['heartland-2026','deer-directory'],indicators=['S05'],resolutionRule='Outcome 1 requires a dated company/government statement explicitly confirming operational completion by the horizon. Outcome 0 is failure of public confirmation by the horizon, not proof the project failed.',rationale='Announced intent and directory evidence support progress, but no commissioning record was found.',createdAt=ASOF),
]
save('forecasts',forecasts)

competitors=[
 ('C01','Thrive Freeze Dry / Mercer','Freeze-dried','Fruit, proteins, pet, probiotics; consolidation',['thrive','thrive-mercer','thrive-oak'],'Oak Creek expansion announced in January 2023; current utilization unverified.','Watch operating milestones, pricing, and geographic consolidation. Do not count Mercer separately.'),
 ('C02','Van Drunen Farms','Freeze-dried','Fruit/vegetable powders, blending, drying alternatives',['vdf'],'Current advertised capability; no new expansion verified.','Watch ingredient innovation, capacity and customer substitution among drying methods.'),
 ('C03','European Freeze Dry','Freeze-dried','Ingredients, contract drying, pet treats',['efd'],'Current advertised capability; capacity volumes unverified.','Watch European energy, capex, export access and toll-drying programs.'),
 ('C04','Barrett Petfood','Freeze-dried; Baked-adjacent','Premium kibble, inclusions, pet manufacturing',['barrett'],'Extrusion and freeze-dried capabilities advertised. Do not equate extrusion with oven baking.','Watch pet capacity, qualification lead times, new plants and contract wins.'),
 ('C05','Weaver Popcorn Manufacturing','Popped','Ready-to-eat and microwave private label/co-manufacturing',['weaver'],'Current capability advertisement; no current utilization verified.','Watch RTE line additions, formats and private-label bids.'),
 ('C06','Flagstone Foods','Roasted','Private-label snack nuts and mixes',['flagstone'],'Company description indexed; full-page verification pending.','Watch roasting, plant consolidation, packaging formats, WARN notices and acquisitions.'),
]
save('competitors',[dict(id=i,name=n,platform=p,overlap=o,sourceIds=s,capacityStatus=c,watch=w,evidenceClass='CONFIRMED' if i!='C06' else 'INFERRED',relationship='Capability overlap; no supplier/customer relationship asserted') for i,n,p,o,s,c,w in competitors])

node_types=['Company','Business Unit','Facility','Process','Production Line','Product Domain','Ingredient Class','Packaging','Utility','Equipment','Transportation Mode','Supplier Geography','Customer Segment','Regulatory Requirement','External Risk']
nodes=[];edges=[]
def node(i,label,kind,cls='INFERRED',refs=None):
    nodes.append(dict(id=i,label=label,type=kind,evidenceClass=cls,sourceIds=refs or [],asOf=ASOF))
def edge(a,b,relation,cls='INFERRED',refs=None,note=''):
    edges.append(dict(id=f'E{len(edges)+1:03}',source=a,target=b,relation=relation,evidenceClass=cls,sourceIds=refs or [],note=note,asOf=ASOF))
node('watershed','Watershed Foods','Company','CONFIRMED',['ws-about'])
node('manna','The Manna Group LLC','Company','HISTORICAL',['edge-2024']);edge('watershed','manna','Joint EDGE party','HISTORICAL',['edge-2024'],'Ownership direction not established')
for i,label in [('human-unit','Human nutrition'),('pet-unit','Pet nutrition')]: node(i,label,'Business Unit','CONFIRMED',['tracegains']);edge('watershed',i,'Advertised division','CONFIRMED',['tracegains'])
for i,label in [('topfox-unit','Top Fox Snacks'),('heartland-unit','Heartland / Aunt Em’s')]:node(i,label,'Business Unit','HISTORICAL',['heartland-2026']);edge('watershed',i,'Reported sister business','HISTORICAL',['heartland-2026'])
for f in facilities:
    node(f['id'],f['name'],'Facility',f['evidenceClass'],f['sourceIds']);edge('watershed',f['id'],'Public presence',f['evidenceClass'],f['sourceIds'],f['precision'])
for p in ['Freeze-dried','Baked','Roasted','Popped']:
    node(p,p,'Process','CONFIRMED',['ws-capabilities']);edge('watershed',p,'Advertises','CONFIRMED',['ws-capabilities'])
    for f in facilities:
        if p in f['platforms']:edge(f['id'],p,'Facility capability','CONFIRMED',f['sourceIds'],'Current throughput and full line allocation not verified')
for p in ['Depositing','Freezing','Traying','Freeze dryer','Packaging line']:
    node('line-'+p,p,'Production Line','HISTORICAL',['edge-2024']);edge('gridley','line-'+p,'Proposed addition','HISTORICAL',['edge-2024'],'2024 project plan; not verified installed')
markets=['Toddler nutrition','Human snacks','Ingredients','Dietary supplements','Pet nutrition','Private label','Contract manufacturing']
for m in markets:node(m,m,'Product Domain','CONFIRMED',['ws-capabilities','ws-about'])
for x in exposures:
    node(x['id'],x['ingredient'],'Ingredient Class','INFERRED',x['sourceIds'])
    for p in x['platforms']:edge(p,x['id'],'Possible input','INFERRED',x['sourceIds'],x['basis'])
    for m in x['markets']:edge(m,x['id'],'Potential exposure','INFERRED',x['sourceIds'])
for i,l in [('film','Film'),('cartons','Cartons'),('labels','Labels'),('pallets','Pallets')]:node(i,l,'Packaging');edge('X15',i,'Candidate material')
for i,l in [('electricity','Electricity'),('gas','Natural gas'),('water','Water')]:
    node(i,l,'Utility')
    for p in ['Freeze-dried','Baked','Roasted','Popped']:edge(p,i,'Potential dependency')
for i,l in [('vacuum','Vacuum / refrigeration'),('ovens','Ovens / roasters'),('controls','PLC / HMI / SCADA'),('packers','Packaging machinery'),('erp','ERP / cloud / identity')]:node(i,l,'Equipment');edge('watershed',i,'Class-level hypothesis')
for i,l in [('truck','Truck'),('reefer','Refrigerated truck'),('rail','Rail / intermodal'),('ocean','Ocean container'),('barge','Barge')]:node(i,l,'Transportation Mode');edge('watershed',i,'Potential lane exposure')
for i,l in [('midwest-crops','Midwest crops'),('west-fruit','Western U.S. fruit origins'),('import-origin','International ingredient origins')]:node(i,l,'Supplier Geography');edge('watershed',i,'Unverified sourcing hypothesis')
for d in json.loads((DATA/'demand.json').read_text()):node(d['id'],d['name'],'Customer Segment');edge('watershed',d['id'],'Target archetype')
for i,l in [('pc-human','Human-food preventive controls'),('pc-animal','Animal-food preventive controls'),('allergens','Allergen / labeling'),('traceability','FSMA traceability'),('supplements','Dietary supplement cGMP / claims'),('importer','FSVP / import requirements'),('sqf','SQF scope verification')]:node(i,l,'Regulatory Requirement');edge('watershed',i,'Applicability review required')
for i,c in enumerate(categories):node('risk-'+str(i),c,'External Risk');edge('watershed','risk-'+str(i),'Monitors')
save('graph',dict(nodeTypes=node_types,nodes=nodes,edges=edges))

save('failure-domains',[
 dict(id='FD01',name='Common crop origin',path='Two fruit vendors → same growing region → same drought/freeze',entities=['Unverified alternative A','Unverified alternative B'],evidenceClass='INFERRED',verify='Tier-2 origin by crop, season and lot; supplier names are not evidence of diversification.'),
 dict(id='FD02',name='Packaging feedstock',path='Two converters → same resin/mill → shared capacity constraint',entities=['Film alternative A','Film alternative B'],evidenceClass='INFERRED',verify='Resin producer, resin grade, backup tooling, converter and mill allocation.'),
 dict(id='FD03',name='Transport chokepoint',path='Two import origins → common port/canal/carrier → correlated delays',entities=['Import lane A','Import lane B'],evidenceClass='INFERRED',verify='Actual port pairs, service strings, transshipment, inland rail corridor.'),
 dict(id='FD04',name='Regional operating footprint',path='Central Illinois facilities → overlapping weather/labor region',entities=['gridley','congerville','deer-creek'],evidenceClass='INFERRED',verify='Facility overlap is public; utilities, labor pools and incident impact correlation require validation.'),
 dict(id='FD05',name='Digital and equipment dependency',path='Production / ERP / recovery → common identity or vendor service',entities=['Identity','ERP','OT support'],evidenceClass='INFERRED',verify='Authorized internal inventory and recovery tests. No public identification of installed systems is assumed.'),
])
print(f'Wrote baseline: {len(facts)} claims, {len(nodes)} nodes, {len(edges)} edges, {len(sources)} sources, {len(signals)} assessments.')
